import { XSD, RDF } from './types'
import type { ClassData, DatatypeVariant, Predicate } from './types'
import { dtTurtle } from './turtle'

function variantToShEx(v: DatatypeVariant): string {
  if (v.datatype === 'IRI') return 'IRI'
  if (v.datatype === 'BlankNode') return 'BNode'
  return dtTurtle(v.datatype)
}

function nodeKindToShEx(nk: string): string {
  if (nk === 'sh:IRI') return 'IRI'
  if (nk === 'sh:BlankNode') return 'BNode'
  if (nk === 'sh:Literal') return 'Literal'
  return '.'
}

function formatCardinality(minCount?: number, maxCount?: number): string {
  const min = (minCount !== undefined && minCount > 0) ? minCount : 0
  const max = (maxCount !== undefined && maxCount > 0) ? maxCount : -1

  if (min === 1 && max === 1) return ''
  if (min === 0 && max === -1) return ' *'
  if (min === 0 && max === 1) return ' ?'
  if (min === 1 && max === -1) return ' +'
  if (max === -1) return ` {${min},}`
  return ` {${min},${max}}`
}

interface ShExLine {
  expr: string    // the triple constraint expression
  comment: string // trailing comment (empty if none)
}

function predicateToShEx(p: Predicate): ShExLine {
  let constraint: string

  if (p.shInStatus === 'done' && Array.isArray(p.shIn) && p.shIn.length > 0) {
    constraint = `[${p.shIn.join(' ')}]`
  } else if (p.variantsStatus === 'done' && p.variants && p.variants.length > 0) {
    const sorted = [...p.variants].sort((a, b) => b.triples - a.triples)
    if (sorted.length === 1) {
      constraint = variantToShEx(sorted[0])
    } else {
      constraint = '(' + sorted.map(v => variantToShEx(v)).join(' OR ') + ')'
    }
  } else if (p.nodeKindStatus === 'done' && p.nodeKinds && p.nodeKinds.length > 0) {
    if (p.nodeKinds.length === 1) {
      constraint = nodeKindToShEx(p.nodeKinds[0].nodeKind)
    } else {
      constraint = '(' + p.nodeKinds.map(nk => nodeKindToShEx(nk.nodeKind)).join(' OR ') + ')'
    }
  } else {
    constraint = '.'
  }

  const card = formatCardinality(p.minCount, p.maxCount)
  let comment = ''
  if (p.languageInStatus === 'done' && p.languageIn && p.languageIn.length > 0) {
    const parts: string[] = [`languageIn: ${p.languageIn.join(' ')}`]
    if (p.uniqueLangStatus === 'done' && p.uniqueLang === true) parts.push('uniqueLang')
    comment = `# ${parts.join('; ')}`
  }
  return { expr: `  <${p.uri}> ${constraint}${card}`, comment }
}

export function generateShEx(
  endpoint: string,
  classDataList: ClassData[],
  _totalTriples: number | null,
): string {
  const lines: string[] = []

  lines.push(`PREFIX xsd: <${XSD}>`)
  lines.push(`PREFIX rdf: <${RDF}>`)
  lines.push('')
  lines.push(`# Generated by shapetrospection from ${endpoint}`)

  for (const { uri: classUri, predicates } of classDataList) {
    const lastSep = Math.max(classUri.lastIndexOf('#'), classUri.lastIndexOf('/'))
    const ns = classUri.substring(0, lastSep + 1)
    const localName = classUri.substring(lastSep + 1)
    const shapeUri = `${ns}${localName}Shape`

    lines.push('')
    lines.push(`# Target class: <${classUri}>`)
    lines.push(`<${shapeUri}> {`)

    for (let i = 0; i < predicates.length; i++) {
      const { expr, comment } = predicateToShEx(predicates[i])
      const sep = i < predicates.length - 1 ? ' ;' : ''
      const suffix = comment ? `${sep}  ${comment}` : sep
      lines.push(expr + suffix)
    }

    lines.push('}')
  }

  return lines.join('\n')
}
